version: '3.7'
services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./syncthing-data:/var/syncthing
      - ./config:/var/syncthing/config
    environment:
      - PUID=1000
      - PGID=1000
